/**
 * Schema OSINAGA-compatible para CSV de PSG.
 *
 * Migrado 1:1 desde legacy-v0/_archived/index.html lineas 1284-1419.
 *
 * - `SCHEMA`: 212 columnas en orden canonico (coincide con el CSV de OSINAGA
 *   generado previamente por IFN).
 * - `MAPPING_INFORME`: mapa snake_case -> etiqueta del formulario IFN.
 * - `EXTRA_INFORME`: campos del formulario IFN que NO existen en el PDF
 *   (se exportan como filas vacias).
 */

export const SCHEMA: ReadonlyArray<string> = [
  'paciente_apellido',
  'paciente_nombre',
  'paciente_sexo',
  'paciente_fecha_nacimiento',
  'paciente_edad_anios',
  'estudio_fecha',
  'estudio_tipo',
  'estudio_software',
  'estudio_epoca_segundos',
  'estudio_criterio_hipopnea',
  'hora_apagado_luces',
  'hora_encendido_luces',
  'tiempo_grabacion_total_min',
  'tiempo_en_cama_min',
  'tiempo_periodo_sueno_min',
  'tiempo_sueno_total_min',
  'eficiencia_sueno_porc',
  'latencia_sueno_min',
  'wake_after_sleep_onset_waso_min',
  'latencia_rem_desde_inicio_sueno_min',
  'latencia_rem_desde_apagado_luces_min',
  'n1_duracion_min',
  'n1_porc_tst',
  'n1_latencia_min',
  'n2_duracion_min',
  'n2_porc_tst',
  'n2_latencia_min',
  'n3_duracion_min',
  'n3_porc_tst',
  'n3_latencia_min',
  'rem_duracion_min',
  'rem_porc_tst',
  'rem_latencia_min',
  'hipnograma_wake_porc',
  'hipnograma_rem_porc',
  'hipnograma_n1_porc',
  'hipnograma_n2_porc',
  'hipnograma_n3_porc',
  'apneas_centrales_numero',
  'apneas_centrales_duracion_media_seg',
  'apneas_centrales_duracion_maxima_seg',
  'apneas_centrales_duracion_total_min',
  'apneas_centrales_porc_tst',
  'apneas_centrales_indice_por_hora',
  'apneas_centrales_recuento_rem',
  'apneas_centrales_recuento_nrem',
  'apneas_centrales_indice_rem',
  'apneas_centrales_indice_nrem',
  'apneas_obstructivas_numero',
  'apneas_obstructivas_duracion_media_seg',
  'apneas_obstructivas_duracion_maxima_seg',
  'apneas_obstructivas_duracion_total_min',
  'apneas_obstructivas_porc_tst',
  'apneas_obstructivas_indice_por_hora',
  'apneas_obstructivas_recuento_rem',
  'apneas_obstructivas_recuento_nrem',
  'apneas_obstructivas_indice_rem',
  'apneas_obstructivas_indice_nrem',
  'apneas_mixtas_numero',
  'apneas_mixtas_duracion_media_seg',
  'apneas_mixtas_duracion_maxima_seg',
  'apneas_mixtas_duracion_total_min',
  'apneas_mixtas_porc_tst',
  'apneas_mixtas_indice_por_hora',
  'apneas_mixtas_recuento_rem',
  'apneas_mixtas_recuento_nrem',
  'apneas_mixtas_indice_rem',
  'apneas_mixtas_indice_nrem',
  'apneas_total_numero',
  'apneas_total_duracion_media_seg',
  'apneas_total_duracion_maxima_seg',
  'apneas_total_duracion_total_min',
  'apneas_total_porc_tst',
  'apneas_total_indice_por_hora',
  'apneas_total_recuento_rem',
  'apneas_total_recuento_nrem',
  'apneas_total_indice_rem',
  'apneas_total_indice_nrem',
  'hipopneas_numero',
  'hipopneas_duracion_media_seg',
  'hipopneas_duracion_maxima_seg',
  'hipopneas_duracion_total_min',
  'hipopneas_porc_tst',
  'hipopneas_indice_por_hora',
  'hipopneas_recuento_rem',
  'hipopneas_recuento_nrem',
  'hipopneas_indice_rem',
  'hipopneas_indice_nrem',
  'iah_eventos_numero',
  'iah_eventos_duracion_media_seg',
  'iah_eventos_duracion_maxima_seg',
  'iah_eventos_duracion_total_min',
  'iah_eventos_porc_tst',
  'iah_global_por_hora',
  'iah_recuento_rem',
  'iah_recuento_nrem',
  'iah_indice_rem_por_hora',
  'iah_indice_nrem_por_hora',
  'rera_numero',
  'rera_duracion_media_seg',
  'rera_duracion_maxima_seg',
  'rera_duracion_total_min',
  'rera_porc_tst',
  'rera_indice_por_hora',
  'rera_recuento_rem',
  'rera_recuento_nrem',
  'eventos_respiratorios_total_numero',
  'eventos_respiratorios_total_duracion_media_seg',
  'eventos_respiratorios_total_duracion_maxima_seg',
  'eventos_respiratorios_total_duracion_total_min',
  'eventos_respiratorios_total_porc_tst',
  'eventos_respiratorios_total_indice_por_hora',
  'rdi_indice_trastornos_respiratorios',
  'pos_supino_duracion_min',
  'pos_supino_iah',
  'pos_no_supino_duracion_min',
  'pos_no_supino_porc_sueno',
  'pos_no_supino_porc_rem',
  'pos_no_supino_porc_nrem',
  'pos_no_supino_apneas_centrales_numero',
  'pos_no_supino_apneas_obstructivas_numero',
  'pos_no_supino_apneas_mixtas_numero',
  'pos_no_supino_hipopneas_numero',
  'pos_no_supino_iah_por_hora',
  'pos_no_supino_rera_numero',
  'pos_no_supino_itr_por_hora',
  'pos_no_supino_desaturaciones_numero',
  'arousal_respiratorio_rem',
  'arousal_respiratorio_nrem',
  'arousal_respiratorio_desp_ligeros',
  'arousal_respiratorio_despertares',
  'arousal_respiratorio_dl_mas_d',
  'arousal_respiratorio_indice_dl_mas_d',
  'arousal_movimiento_piernas_rem',
  'arousal_movimiento_piernas_nrem',
  'arousal_movimiento_piernas_desp_ligeros',
  'arousal_movimiento_piernas_despertares',
  'arousal_movimiento_piernas_dl_mas_d',
  'arousal_movimiento_piernas_indice_dl_mas_d',
  'arousal_ronquidos_rem',
  'arousal_ronquidos_nrem',
  'arousal_ronquidos_desp_ligeros',
  'arousal_ronquidos_despertares',
  'arousal_ronquidos_dl_mas_d',
  'arousal_ronquidos_indice_dl_mas_d',
  'arousal_espontaneo_rem',
  'arousal_espontaneo_nrem',
  'arousal_espontaneo_desp_ligeros',
  'arousal_espontaneo_despertares',
  'arousal_espontaneo_dl_mas_d',
  'arousal_espontaneo_indice_dl_mas_d',
  'arousal_total_rem',
  'arousal_total_nrem',
  'arousal_total_desp_ligeros',
  'arousal_total_despertares',
  'arousal_total_dl_mas_d',
  'arousal_total_indice_dl_mas_d',
  'indice_despertares_ligeros_rem',
  'indice_despertares_ligeros_nrem',
  'indice_despertares_ligeros_global',
  'indice_despertares_completos',
  'movimientos_piernas_total_recuento',
  'movimientos_piernas_total_indice_por_hora',
  'mpe_movimientos_periodicos_recuento',
  'mpe_movimientos_periodicos_indice_por_hora',
  'mpe_con_arousal_recuento',
  'mpe_con_arousal_indice_por_hora',
  'ronquidos_episodios_numero',
  'ronquidos_tiempo_total_min',
  'spo2_media_despertar_porc',
  'spo2_media_nrem_porc',
  'spo2_media_rem_porc',
  'spo2_media_total_porc',
  'spo2_minima_porc',
  'desaturaciones_relevantes_despertar_numero',
  'desaturaciones_relevantes_nrem_numero',
  'desaturaciones_relevantes_rem_numero',
  'desaturaciones_relevantes_total_numero',
  'odi_indice_desaturacion_calculado_por_hora',
  'spo2_menor_95_despertar_min',
  'spo2_menor_95_despertar_porc',
  'spo2_menor_95_nrem_min',
  'spo2_menor_95_nrem_porc',
  'spo2_menor_95_rem_min',
  'spo2_menor_95_rem_porc',
  'spo2_menor_95_tc_min',
  'spo2_menor_95_tc_porc',
  'spo2_menor_90_despertar_min',
  'spo2_menor_90_despertar_porc',
  'spo2_menor_90_nrem_min',
  'spo2_menor_90_nrem_porc',
  'spo2_menor_90_rem_min',
  'spo2_menor_90_rem_porc',
  'spo2_menor_90_tc_min',
  'spo2_menor_90_tc_porc',
  't90_tiempo_spo2_menor_90_min',
  'spo2_menor_85_tc_min',
  'spo2_menor_85_tc_porc',
  'spo2_menor_80_tc_min',
  'spo2_menor_80_tc_porc',
  'spo2_menor_75_tc_min',
  'spo2_menor_75_tc_porc',
  'spo2_menor_70_tc_min',
  'spo2_menor_70_tc_porc',
  'spo2_menor_60_tc_min',
  'spo2_menor_60_tc_porc',
  'spo2_menor_50_tc_min',
  'spo2_menor_50_tc_porc',
  'spo2_artefacto_despertar_min',
  'spo2_artefacto_nrem_min',
  'spo2_artefacto_rem_min',
  'spo2_artefacto_tc_min',
  'cpap_uso_promedio_min',
  'cpap_dias_uso',
  'cpap_dias_total',
  'cpap_dias_4h_porc',
  'cpap_presion_mediana_cmh2o',
  'cpap_presion_p95_cmh2o',
  'cpap_fuga_p95_lpm',
  'cheyne_stokes_porc',
  'fc_media_sueno_lpm',
  'fc_minima_lpm',
  'fc_maxima_lpm',
  'estudio_fecha_fin',
];

/** Mapa snake_case -> etiqueta exacta del formulario IFN. */
export const MAPPING_INFORME: Readonly<Record<string, string>> = {
  // Arquitectura del sueño
  tiempo_grabacion_total_min: 'Tiempo de grabación total (TGT)',
  eficiencia_sueno_porc: 'Eficiencia de Sueño',
  latencia_sueno_min: 'Latencia',
  wake_after_sleep_onset_waso_min: 'DTIS/WASO',
  latencia_rem_desde_inicio_sueno_min: 'Latencia REM',
  n1_porc_tst: 'Superficial N1',
  n2_porc_tst: 'Superficial N2',
  n3_porc_tst: 'Sueño profundo N3',
  rem_porc_tst: 'REM',
  // MPP
  mpe_con_arousal_indice_por_hora: 'Despertares Ligeros por MPE',
  mpe_movimientos_periodicos_indice_por_hora: 'Indice MPP TST',
  // Apneas
  apneas_obstructivas_numero: 'Obstructivas',
  apneas_obstructivas_duracion_maxima_seg: 'Obstructivas duración máxima (en segundos)',
  apneas_centrales_numero: 'Centrales',
  apneas_centrales_duracion_maxima_seg: 'Centrales duración máxima (en segundos)',
  apneas_mixtas_numero: 'Mixtas',
  apneas_mixtas_duracion_maxima_seg: 'Mixtas duración máxima (en segundos)',
  hipopneas_numero: 'Hipoapneas',
  hipopneas_duracion_maxima_seg: 'Hipoapneas duración máxima (en segundos)',
  iah_eventos_numero: 'Totales en el Estudio',
  // Saturación
  spo2_media_total_porc: 'Saturación Promedio',
  spo2_minima_porc: 'Saturación Min',
  // REM IPR
  iah_recuento_rem: 'Obstructivas en REM',
  iah_recuento_nrem: 'Obstructivas en NREM',
  iah_indice_rem_por_hora: 'Indice REM (IPR)',
  iah_indice_nrem_por_hora: 'Indice NREM (IPR)',
  eventos_respiratorios_total_numero: 'IPR total de la noche',
};

/** Campos del formulario IFN que NO existen en el PDF (filas vacias en CSV). */
export const EXTRA_INFORME: ReadonlyArray<readonly [string, string]> = [
  ['distribucion_sueno', 'Distribución del sueño'],
  ['descripcion_arquitectura_sueno', 'Descripción (arquitectura del sueño)'],
  ['comentario_adicional_arquitectura_sueno', 'Comentario adicional (arquitectura del sueño)'],
  ['indice_mpp_rem', 'Indice MPP REM'],
  ['indice_mpp_nrem', 'Indice MPP NREM'],
  ['rera_eventos_hiperresistencia_si_no', 'RERA / Eventos de Hiperresistencia'],
  ['ronquidos_regularidad', 'Ronquidos'],
  ['ronquido_intensidad', 'Ronquido'],
  ['patron_sat', 'Patrón SAT'],
  ['tiempo_bajo_86_porc_min', 'Tiempo bajo 86%'],
  ['saturacion_basal_porc', 'Saturacion Basal'],
  ['cheyne_stokes_porc', 'Cheyne Stokes'],
  ['arritmias_si_no', 'Arritmias'],
  ['comentario_adicional_cardio', 'Comentario Adicional (Cardio)'],
  ['conclusion_general', 'Conclusión General'],
  ['recomendaciones_generales', 'Recomendaciones Generales'],
  ['evolucion_estudios_previos', 'Evolución Estudios Previos'],
  ['calidad_inicio_despues_22', 'Inició después de 22:00'],
  ['calidad_duracion_7hs_o_mas', 'Duró 7hs o más'],
  ['calidad_senal', 'Buena calidad señal'],
  ['calidad_oximetria', 'Buena calidad oxi'],
  ['calidad_piernas', 'Buena calidad piernas'],
  ['calidad_termino_en_rem', 'Terminó en REM'],
  ['calificacion_general_estudio', 'Calificación General del Estudio'],
  ['sintesis_del_estudio', 'Síntesis del Estudio'],
];
